create type "public"."character_category" as enum ('human', 'nonhuman');

create type "public"."game_status" as enum ('draft', 'review', 'published', 'archived');

create type "public"."types" as enum ('action', 'sense', 'landmark', 'history', 'nature');

create type "public"."visibility" as enum ('private', 'unlisted', 'public');

CREATE EXTENSION IF NOT EXISTS postgis;

  create table "public"."ai_companion_configs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "game_id" bigint,
    "name" text,
    "system_prompt" text,
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."ai_companion_configs" enable row level security;


  create table "public"."cards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "game_id" bigint,
    "slug" text,
    "title" text,
    "prompt" text,
    "applies_to" text[],
    "hero_steps" integer[],
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."cards" enable row level security;


  create table "public"."characters" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "game_id" bigint,
    "category" public.character_category default 'nonhuman'::public.character_category,
    "name" text,
    "summary" text,
    "image_url" text,
    "updated_at" timestamp with time zone default now(),
    "slug" text
      );


alter table "public"."characters" enable row level security;


  create table "public"."games" (
    "id" bigint generated by default as identity not null,
    "owner_id" uuid,
    "title" text default '''New game'''::text,
    "description" text default ''::text,
    "image_url" text,
    "categories" text[],
    "status" public.game_status default 'draft'::public.game_status,
    "visibility" public.visibility default 'private'::public.visibility,
    "url_slug" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "location" geometry(Point, 4326) NOT NULL,
    "game_id" uuid default gen_random_uuid()
      );


alter table "public"."games" enable row level security;


  create table "public"."pois" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "game_id" bigint not null,
    "name" text not null default ''::text,
    "description" text,
    "image_url" text,
    "type" public.types not null default 'landmark'::public.types,
    "tags" text[],
    "updated_at" timestamp with time zone default now(),
    "location" geometry(Point, 4326) NOT NULL,
    "slug" text not null
      );


alter table "public"."pois" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "full_name" text,
    "avatar_url" text,
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX ai_companion_configs_pkey ON public.ai_companion_configs USING btree (id);

CREATE UNIQUE INDEX cards_pkey ON public.cards USING btree (id);

CREATE UNIQUE INDEX characters_pkey ON public.characters USING btree (id);

CREATE UNIQUE INDEX games_pkey ON public.games USING btree (id);

CREATE UNIQUE INDEX games_url_slug_key ON public.games USING btree (url_slug);

CREATE INDEX idx_games_owner ON public.games USING btree (owner_id);

CREATE INDEX idx_games_updated_at ON public.games USING btree (updated_at DESC);

CREATE UNIQUE INDEX pois_pkey ON public.pois USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."ai_companion_configs" add constraint "ai_companion_configs_pkey" PRIMARY KEY using index "ai_companion_configs_pkey";

alter table "public"."cards" add constraint "cards_pkey" PRIMARY KEY using index "cards_pkey";

alter table "public"."characters" add constraint "characters_pkey" PRIMARY KEY using index "characters_pkey";

alter table "public"."games" add constraint "games_pkey" PRIMARY KEY using index "games_pkey";

alter table "public"."pois" add constraint "pois_pkey" PRIMARY KEY using index "pois_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."ai_companion_configs" add constraint "ai_companion_configs_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE not valid;

alter table "public"."ai_companion_configs" validate constraint "ai_companion_configs_game_id_fkey";

alter table "public"."cards" add constraint "cards_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE not valid;

alter table "public"."cards" validate constraint "cards_game_id_fkey";

alter table "public"."characters" add constraint "characters_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE not valid;

alter table "public"."characters" validate constraint "characters_game_id_fkey";

alter table "public"."games" add constraint "games_location_check" CHECK ((st_srid(location) = 4326)) not valid;
alter table "public"."games" validate constraint "games_location_check";

alter table "public"."games" add constraint "games_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."games" validate constraint "games_owner_id_fkey";

alter table "public"."games" add constraint "games_url_slug_key" UNIQUE using index "games_url_slug_key";

alter table "public"."pois" add constraint "pois_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE not valid;

alter table "public"."pois" validate constraint "pois_game_id_fkey";

alter table "public"."pois" add constraint "pois_location_check" CHECK ((st_srid(location) = 4326)) not valid;

alter table "public"."pois" validate constraint "pois_location_check";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

CREATE INDEX IF NOT EXISTS games_location_idx ON public.games USING GIST (location);

CREATE INDEX IF NOT EXISTS pois_location_idx ON public.pois USING GIST (location);

CREATE OR REPLACE FUNCTION public.gen_card_slug()
 RETURNS text
 LANGUAGE sql
AS $function$
  select 'card-' || substr(encode(gen_random_bytes(6), 'hex'), 1, 8)
$function$
;

CREATE OR REPLACE FUNCTION public.gen_character_slug()
 RETURNS text
 LANGUAGE sql
AS $function$
  select 'char-' || substr(encode(gen_random_bytes(6), 'hex'), 1, 8)
$function$
;

CREATE OR REPLACE FUNCTION public.gen_poi_slug()
 RETURNS text
 LANGUAGE sql
AS $function$
  select 'poi-' || substr(encode(gen_random_bytes(6), 'hex'), 1, 8)
$function$
;

CREATE OR REPLACE FUNCTION public.get_slug()
 RETURNS text
 LANGUAGE sql
AS $function$
  select 'game-' || substr(encode(gen_random_bytes(6), 'hex'), 1, 8)
$function$
;

CREATE OR REPLACE FUNCTION public.handle_cards_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if new.slug is null then
    new.slug := public.gen_card_slug();
  end if;
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.handle_characters_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if new.slug is null then
    new.slug := public.gen_character_slug();
  end if;
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.handle_games_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if new.url_slug is null then
    new.url_slug := public.gen_slug();
  end if;
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  m jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  -- Try to pick a decent default name
  name text := coalesce(
    m->>'full_name',
    m->>'name',
    split_part(new.email, '@', 1)
  );
  avatar text := m->>'avatar_url';
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, name, avatar)
  on conflict (id) do nothing;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_pois_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if new.slug is null then
    new.slug := public.gen_poi_slug();
  end if;
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.set_my_name(p_name text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update public.profiles
  set full_name = p_name
  where id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin new.updated_at := now(); return new; end $function$
;

grant delete on table "public"."ai_companion_configs" to "anon";

grant insert on table "public"."ai_companion_configs" to "anon";

grant references on table "public"."ai_companion_configs" to "anon";

grant select on table "public"."ai_companion_configs" to "anon";

grant trigger on table "public"."ai_companion_configs" to "anon";

grant truncate on table "public"."ai_companion_configs" to "anon";

grant update on table "public"."ai_companion_configs" to "anon";

grant delete on table "public"."ai_companion_configs" to "authenticated";

grant insert on table "public"."ai_companion_configs" to "authenticated";

grant references on table "public"."ai_companion_configs" to "authenticated";

grant select on table "public"."ai_companion_configs" to "authenticated";

grant trigger on table "public"."ai_companion_configs" to "authenticated";

grant truncate on table "public"."ai_companion_configs" to "authenticated";

grant update on table "public"."ai_companion_configs" to "authenticated";

grant delete on table "public"."ai_companion_configs" to "service_role";

grant insert on table "public"."ai_companion_configs" to "service_role";

grant references on table "public"."ai_companion_configs" to "service_role";

grant select on table "public"."ai_companion_configs" to "service_role";

grant trigger on table "public"."ai_companion_configs" to "service_role";

grant truncate on table "public"."ai_companion_configs" to "service_role";

grant update on table "public"."ai_companion_configs" to "service_role";

grant delete on table "public"."cards" to "anon";

grant insert on table "public"."cards" to "anon";

grant references on table "public"."cards" to "anon";

grant select on table "public"."cards" to "anon";

grant trigger on table "public"."cards" to "anon";

grant truncate on table "public"."cards" to "anon";

grant update on table "public"."cards" to "anon";

grant delete on table "public"."cards" to "authenticated";

grant insert on table "public"."cards" to "authenticated";

grant references on table "public"."cards" to "authenticated";

grant select on table "public"."cards" to "authenticated";

grant trigger on table "public"."cards" to "authenticated";

grant truncate on table "public"."cards" to "authenticated";

grant update on table "public"."cards" to "authenticated";

grant delete on table "public"."cards" to "service_role";

grant insert on table "public"."cards" to "service_role";

grant references on table "public"."cards" to "service_role";

grant select on table "public"."cards" to "service_role";

grant trigger on table "public"."cards" to "service_role";

grant truncate on table "public"."cards" to "service_role";

grant update on table "public"."cards" to "service_role";

grant delete on table "public"."characters" to "anon";

grant insert on table "public"."characters" to "anon";

grant references on table "public"."characters" to "anon";

grant select on table "public"."characters" to "anon";

grant trigger on table "public"."characters" to "anon";

grant truncate on table "public"."characters" to "anon";

grant update on table "public"."characters" to "anon";

grant delete on table "public"."characters" to "authenticated";

grant insert on table "public"."characters" to "authenticated";

grant references on table "public"."characters" to "authenticated";

grant select on table "public"."characters" to "authenticated";

grant trigger on table "public"."characters" to "authenticated";

grant truncate on table "public"."characters" to "authenticated";

grant update on table "public"."characters" to "authenticated";

grant delete on table "public"."characters" to "service_role";

grant insert on table "public"."characters" to "service_role";

grant references on table "public"."characters" to "service_role";

grant select on table "public"."characters" to "service_role";

grant trigger on table "public"."characters" to "service_role";

grant truncate on table "public"."characters" to "service_role";

grant update on table "public"."characters" to "service_role";

grant delete on table "public"."games" to "anon";

grant insert on table "public"."games" to "anon";

grant references on table "public"."games" to "anon";

grant select on table "public"."games" to "anon";

grant trigger on table "public"."games" to "anon";

grant truncate on table "public"."games" to "anon";

grant update on table "public"."games" to "anon";

grant delete on table "public"."games" to "authenticated";

grant insert on table "public"."games" to "authenticated";

grant references on table "public"."games" to "authenticated";

grant select on table "public"."games" to "authenticated";

grant trigger on table "public"."games" to "authenticated";

grant truncate on table "public"."games" to "authenticated";

grant update on table "public"."games" to "authenticated";

grant delete on table "public"."games" to "service_role";

grant insert on table "public"."games" to "service_role";

grant references on table "public"."games" to "service_role";

grant select on table "public"."games" to "service_role";

grant trigger on table "public"."games" to "service_role";

grant truncate on table "public"."games" to "service_role";

grant update on table "public"."games" to "service_role";

grant delete on table "public"."pois" to "anon";

grant insert on table "public"."pois" to "anon";

grant references on table "public"."pois" to "anon";

grant select on table "public"."pois" to "anon";

grant trigger on table "public"."pois" to "anon";

grant truncate on table "public"."pois" to "anon";

grant update on table "public"."pois" to "anon";

grant delete on table "public"."pois" to "authenticated";

grant insert on table "public"."pois" to "authenticated";

grant references on table "public"."pois" to "authenticated";

grant select on table "public"."pois" to "authenticated";

grant trigger on table "public"."pois" to "authenticated";

grant truncate on table "public"."pois" to "authenticated";

grant update on table "public"."pois" to "authenticated";

grant delete on table "public"."pois" to "service_role";

grant insert on table "public"."pois" to "service_role";

grant references on table "public"."pois" to "service_role";

grant select on table "public"."pois" to "service_role";

grant trigger on table "public"."pois" to "service_role";

grant truncate on table "public"."pois" to "service_role";

grant update on table "public"."pois" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "ai_cfg_delete_by_owner"
  on "public"."ai_companion_configs"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = ai_companion_configs.game_id) AND (g.owner_id = auth.uid())))));



  create policy "ai_cfg_insert_by_owner_non_anon"
  on "public"."ai_companion_configs"
  as permissive
  for insert
  to authenticated
with check (((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = ai_companion_configs.game_id) AND (g.owner_id = auth.uid())))) AND (COALESCE(((current_setting('request.jwt.claims'::text, true))::jsonb ->> 'is_anonymous'::text), 'false'::text) = 'false'::text)));



  create policy "ai_cfg_select_by_owner"
  on "public"."ai_companion_configs"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = ai_companion_configs.game_id) AND (g.owner_id = auth.uid())))));



  create policy "ai_cfg_update_by_owner"
  on "public"."ai_companion_configs"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = ai_companion_configs.game_id) AND (g.owner_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = ai_companion_configs.game_id) AND (g.owner_id = auth.uid())))));



  create policy "cards_delete_by_owner"
  on "public"."cards"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = cards.game_id) AND (g.owner_id = auth.uid())))));



  create policy "cards_insert_by_owner"
  on "public"."cards"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = cards.game_id) AND (g.owner_id = auth.uid())))));



  create policy "cards_select_by_owner"
  on "public"."cards"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = cards.game_id) AND (g.owner_id = auth.uid())))));



  create policy "cards_update_by_owner"
  on "public"."cards"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = cards.game_id) AND (g.owner_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = cards.game_id) AND (g.owner_id = auth.uid())))));



  create policy "characters_delete_by_owner"
  on "public"."characters"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = characters.game_id) AND (g.owner_id = auth.uid())))));



  create policy "characters_insert_by_owner"
  on "public"."characters"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = characters.game_id) AND (g.owner_id = auth.uid())))));



  create policy "characters_select_by_owner"
  on "public"."characters"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = characters.game_id) AND (g.owner_id = auth.uid())))));



  create policy "characters_update_by_owner"
  on "public"."characters"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = characters.game_id) AND (g.owner_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = characters.game_id) AND (g.owner_id = auth.uid())))));



  create policy "games_delete_own"
  on "public"."games"
  as permissive
  for delete
  to authenticated
using ((owner_id = auth.uid()));



  create policy "games_insert_non_anonymous"
  on "public"."games"
  as permissive
  for insert
  to authenticated
with check (((owner_id = auth.uid()) AND (COALESCE(((current_setting('request.jwt.claims'::text, true))::jsonb ->> 'is_anonymous'::text), 'false'::text) = 'false'::text)));



  create policy "games_select_own"
  on "public"."games"
  as permissive
  for select
  to authenticated
using ((owner_id = auth.uid()));



  create policy "games_update_own"
  on "public"."games"
  as permissive
  for update
  to authenticated
using ((owner_id = auth.uid()))
with check ((owner_id = auth.uid()));



  create policy "pois_delete_by_owner"
  on "public"."pois"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = pois.game_id) AND (g.owner_id = auth.uid())))));



  create policy "pois_insert_by_owner"
  on "public"."pois"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = pois.game_id) AND (g.owner_id = auth.uid())))));



  create policy "pois_select_by_owner"
  on "public"."pois"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = pois.game_id) AND (g.owner_id = auth.uid())))));



  create policy "pois_update_by_owner"
  on "public"."pois"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = pois.game_id) AND (g.owner_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.games g
  WHERE ((g.id = pois.game_id) AND (g.owner_id = auth.uid())))));



  create policy "insert own profile"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((id = auth.uid()));



  create policy "read own profile"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((id = auth.uid()));



  create policy "update own profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((id = auth.uid()))
with check ((id = auth.uid()));


CREATE TRIGGER trg_ai_cfg_updated_at BEFORE UPDATE ON public.ai_companion_configs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_cards_before_insert BEFORE INSERT ON public.cards FOR EACH ROW EXECUTE FUNCTION public.handle_cards_before_insert();

CREATE TRIGGER trg_cards_updated_at BEFORE UPDATE ON public.cards FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_characters_before_insert BEFORE INSERT ON public.characters FOR EACH ROW EXECUTE FUNCTION public.handle_characters_before_insert();

CREATE TRIGGER trg_characters_updated_at BEFORE UPDATE ON public.characters FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_games_before_insert BEFORE INSERT ON public.games FOR EACH ROW EXECUTE FUNCTION public.handle_games_before_insert();

CREATE TRIGGER trg_games_updated_at BEFORE UPDATE ON public.games FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_pois_before_insert BEFORE INSERT ON public.pois FOR EACH ROW EXECUTE FUNCTION public.handle_pois_before_insert();

CREATE TRIGGER trg_pois_updated_at BEFORE UPDATE ON public.pois FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


