-- ============================================================
-- Migration: add_play_tables
-- Date: 2026-03-20
-- Description: Adds game session, story segment, and story tables
--              plus RLS policies for players and new RPC functions.
-- ============================================================

-- ------------------------------------------------------------
-- 1. New enums
-- ------------------------------------------------------------

CREATE TYPE public.play_mode AS ENUM ('gps', 'remote');
CREATE TYPE public.session_status AS ENUM ('setup', 'active', 'completed', 'abandoned');
CREATE TYPE public.segment_type AS ENUM ('introduction', 'step', 'deepening', 'reflection');

-- ------------------------------------------------------------
-- 2. New tables
-- ------------------------------------------------------------

CREATE TABLE public.game_sessions (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id        uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
  player_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  game_id           bigint NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  character_id      uuid REFERENCES public.characters(character_id) ON DELETE SET NULL,
  character_name    text NOT NULL DEFAULT '',
  play_mode         public.play_mode NOT NULL DEFAULT 'gps',
  current_hero_step public.hero_steps,
  status            public.session_status NOT NULL DEFAULT 'setup',
  started_at        timestamptz DEFAULT now(),
  completed_at      timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz DEFAULT now()
);

CREATE TABLE public.story_segments (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id     bigint NOT NULL REFERENCES public.game_sessions(id) ON DELETE CASCADE,
  poi_id         bigint REFERENCES public.pois(id) ON DELETE SET NULL,
  card_id        bigint REFERENCES public.cards(id) ON DELETE SET NULL,
  hero_step      public.hero_steps,
  segment_type   public.segment_type NOT NULL,
  content        text NOT NULL DEFAULT '',
  segment_order  integer NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);

CREATE TABLE public.stories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id    uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
  session_id  bigint NOT NULL UNIQUE REFERENCES public.game_sessions(id) ON DELETE CASCADE,
  title       text NOT NULL DEFAULT '',
  is_public   boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

-- ------------------------------------------------------------
-- 3. Enable RLS on new tables
-- ------------------------------------------------------------

ALTER TABLE public.game_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.story_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- 4. Grants for new tables
-- ------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.game_sessions TO authenticated;
GRANT SELECT ON public.game_sessions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.story_segments TO authenticated;
GRANT SELECT ON public.story_segments TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stories TO authenticated;
GRANT SELECT ON public.stories TO anon;

-- ------------------------------------------------------------
-- 5. RLS policies on EXISTING tables — allow players to read published games
-- ------------------------------------------------------------

-- Published games readable by all (anon = not yet signed in, authenticated = signed in or anonymous JWT)
CREATE POLICY "games_select_published"
  ON public.games AS PERMISSIVE FOR SELECT TO anon, authenticated
  USING (status = 'published' AND visibility = 'public');

CREATE POLICY "pois_select_published"
  ON public.pois AS PERMISSIVE FOR SELECT TO anon, authenticated
  USING (EXISTS (
    SELECT 1 FROM public.games g
    WHERE g.id = pois.game_id
      AND g.status = 'published'
      AND g.visibility = 'public'
  ));

CREATE POLICY "characters_select_published"
  ON public.characters AS PERMISSIVE FOR SELECT TO anon, authenticated
  USING (EXISTS (
    SELECT 1 FROM public.games g
    WHERE g.id = characters.game_id
      AND g.status = 'published'
      AND g.visibility = 'public'
  ));

CREATE POLICY "cards_select_published"
  ON public.cards AS PERMISSIVE FOR SELECT TO anon, authenticated
  USING (EXISTS (
    SELECT 1 FROM public.games g
    WHERE g.id = cards.game_id
      AND g.status = 'published'
      AND g.visibility = 'public'
  ));

-- ------------------------------------------------------------
-- 6. RLS policies on new tables
-- ------------------------------------------------------------

-- game_sessions: players own their rows
CREATE POLICY "game_sessions_select_own"
  ON public.game_sessions AS PERMISSIVE FOR SELECT TO authenticated
  USING (player_id = auth.uid());

CREATE POLICY "game_sessions_insert_own"
  ON public.game_sessions AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (player_id = auth.uid());

CREATE POLICY "game_sessions_update_own"
  ON public.game_sessions AS PERMISSIVE FOR UPDATE TO authenticated
  USING (player_id = auth.uid())
  WITH CHECK (player_id = auth.uid());

-- story_segments: players own via session
CREATE POLICY "story_segments_select_own"
  ON public.story_segments AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = story_segments.session_id
      AND gs.player_id = auth.uid()
  ));

CREATE POLICY "story_segments_insert_own"
  ON public.story_segments AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = story_segments.session_id
      AND gs.player_id = auth.uid()
  ));

CREATE POLICY "story_segments_update_own"
  ON public.story_segments AS PERMISSIVE FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = story_segments.session_id
      AND gs.player_id = auth.uid()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = story_segments.session_id
      AND gs.player_id = auth.uid()
  ));

-- stories: player CRUD own; public SELECT if is_public=true
CREATE POLICY "stories_select_own"
  ON public.stories AS PERMISSIVE FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = stories.session_id
      AND gs.player_id = auth.uid()
  ));

CREATE POLICY "stories_select_public"
  ON public.stories AS PERMISSIVE FOR SELECT TO anon
  USING (is_public = true);

CREATE POLICY "stories_select_public_authenticated"
  ON public.stories AS PERMISSIVE FOR SELECT TO authenticated
  USING (is_public = true);

CREATE POLICY "stories_insert_own"
  ON public.stories AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = stories.session_id
      AND gs.player_id = auth.uid()
  ));

CREATE POLICY "stories_update_own"
  ON public.stories AS PERMISSIVE FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = stories.session_id
      AND gs.player_id = auth.uid()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = stories.session_id
      AND gs.player_id = auth.uid()
  ));

CREATE POLICY "stories_delete_own"
  ON public.stories AS PERMISSIVE FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.game_sessions gs
    WHERE gs.id = stories.session_id
      AND gs.player_id = auth.uid()
  ));

-- story_segments of public stories: readable by anyone (for public story viewer)
CREATE POLICY "story_segments_select_public_story"
  ON public.story_segments AS PERMISSIVE FOR SELECT TO anon, authenticated
  USING (EXISTS (
    SELECT 1 FROM public.stories s
    WHERE s.session_id = story_segments.session_id AND s.is_public = true
  ));

-- game_sessions of public stories: readable by anyone (needed for story viewer join)
CREATE POLICY "game_sessions_select_public_story"
  ON public.game_sessions AS PERMISSIVE FOR SELECT TO anon, authenticated
  USING (EXISTS (
    SELECT 1 FROM public.stories s
    WHERE s.session_id = game_sessions.id AND s.is_public = true
  ));

-- ------------------------------------------------------------
-- 7. Updated_at triggers for new tables
-- ------------------------------------------------------------

CREATE TRIGGER trg_game_sessions_updated_at
  BEFORE UPDATE ON public.game_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_story_segments_updated_at
  BEFORE UPDATE ON public.story_segments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_stories_updated_at
  BEFORE UPDATE ON public.stories
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ------------------------------------------------------------
-- 8. Indexes
-- ------------------------------------------------------------

CREATE INDEX idx_game_sessions_player_id ON public.game_sessions(player_id);
CREATE INDEX idx_game_sessions_game_id ON public.game_sessions(game_id);
CREATE INDEX idx_story_segments_session_id ON public.story_segments(session_id);

-- ------------------------------------------------------------
-- 9. RPC functions
-- ------------------------------------------------------------

-- Browse: all published games with flat coordinates + distance from user
CREATE OR REPLACE FUNCTION public.get_published_games_with_distance(
  user_lng double precision,
  user_lat double precision
)
RETURNS TABLE (
  id bigint,
  game_id uuid,
  title text,
  description text,
  image_url text,
  longitude double precision,
  latitude double precision,
  distance_meters double precision
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    g.id,
    g.game_id,
    g.title,
    g.description,
    g.image_url,
    ST_X(g.location::geometry) AS longitude,
    ST_Y(g.location::geometry) AS latitude,
    ST_Distance(
      g.location::geography,
      ST_SetSRID(ST_MakePoint(user_lng, user_lat), 4326)::geography
    ) AS distance_meters
  FROM public.games g
  WHERE g.status = 'published'
    AND g.visibility = 'public'
  ORDER BY distance_meters;
END;
$$;

-- Gameplay: POIs with flat coordinates for a published game
CREATE OR REPLACE FUNCTION public.get_game_pois_for_player(
  game_id_param bigint
)
RETURNS TABLE (
  id bigint,
  name text,
  description text,
  image_url text,
  type public.types,
  tags text[],
  longitude double precision,
  latitude double precision
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.name,
    p.description,
    p.image_url,
    p.type,
    p.tags,
    ST_X(p.location::geometry) AS longitude,
    ST_Y(p.location::geometry) AS latitude
  FROM public.pois p
  JOIN public.games g ON g.id = p.game_id
  WHERE p.game_id = game_id_param
    AND g.status = 'published'
    AND g.visibility = 'public'
  ORDER BY p.created_at;
END;
$$;

-- GPS gate: server-side authoritative proximity check
CREATE OR REPLACE FUNCTION public.check_poi_proximity(
  poi_id_param bigint,
  user_lng double precision,
  user_lat double precision,
  radius_meters double precision DEFAULT 100
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  within_range boolean;
BEGIN
  SELECT ST_DWithin(
    p.location::geography,
    ST_SetSRID(ST_MakePoint(user_lng, user_lat), 4326)::geography,
    radius_meters
  ) INTO within_range
  FROM public.pois p
  WHERE p.id = poi_id_param;

  RETURN COALESCE(within_range, false);
END;
$$;

-- ------------------------------------------------------------
-- 10. Grants on RPC functions
-- ------------------------------------------------------------

GRANT EXECUTE ON FUNCTION public.get_published_games_with_distance(double precision, double precision) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_games_with_distance(double precision, double precision) TO anon;
GRANT EXECUTE ON FUNCTION public.get_game_pois_for_player(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_game_pois_for_player(bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.check_poi_proximity(bigint, double precision, double precision, double precision) TO authenticated;
-- Also grant anon access to the existing get_game_location RPC (needed for public game info page)
GRANT EXECUTE ON FUNCTION public.get_game_location(bigint) TO anon;
